### ISSUE TITLE
can't build project 

### ISSUE THREAD

**Issue by johndpope** [gavineadie/Geometries#1]
Hi Gavin,

I was trawling through github searching for Celestial Sphere scenekit and struck your repo. 

<img width="1201" alt="screen shot 2017-11-17 at 8 53 16 pm" src="https://user-images.githubusercontent.com/289994/32975806-60c4281a-cbd9-11e7-8f7e-e51e40f051df.png">

I'm attempting to update this project - to use a geocentric point of view.
It's using swiftAA + ARKit, you may be interested. 
https://github.com/ThumbWorks/AugmentedSolarSystem/issues/46

I noticed you project depends on another repo - satkit.
I actually don't need satellites but she won't build without these files. 
I'll try reversing some commits to older code base. thanks in advance if you respond.

**Comment by gavineadie** [comment]
Let me have a look; I’ve not looked at Geometries recently .. I have a few private libraries; I’ll see what I can free up .. Gavin

**Comment by gavineadie** [comment]
There’s a branch that will build without any satellites involved .. best luck, Gavin

**Comment by johndpope** [comment]
seems like it still depends on your satkit project.
I tried commenting out  the import statement, but no joy. 
I've captured the functions that app depends on - perhaps a gist with those functions maybe a get out of jail card for me.

do you have any astro calculation books you'd recommend for newbie ?

not sure if it could help.  but there is a library for astronomical calculations called swiftAA
https://github.com/onekiloparsec/SwiftAA


<img width="919" alt="screen shot 2017-11-18 at 18 22 17" src="https://user-images.githubusercontent.com/289994/32985637-6ed553de-cc8d-11e7-8d31-bfcae212b50b.png">



<img width="906" alt="screen shot 2017-11-18 at 18 14 47" src="https://user-images.githubusercontent.com/289994/32985574-634aceb4-cc8c-11e7-9b1e-c84634ed0feb.png">

<img width="850" alt="screen shot 2017-11-18 at 18 18 38" src="https://user-images.githubusercontent.com/289994/32985610-f04a198c-cc8c-11e7-8f61-31f728d1ec1f.png">
<img width="906" alt="screen shot 2017-11-18 at 18 14 47" src="https://user-images.githubusercontent.com/289994/32985611-f054ef2e-cc8c-11e7-900c-433d38f13c6a.png">

**Comment by johndpope** [comment]
I think I can piece things back together from pre satkit. no worries.

public func ZeroMeanSiderealTimeDegrees(julianDate:Double) -> Double {
    let     fractionalDay = fmod(julianDate + 0.5, 1.0)         // fractional part of JD + half a day
    let     adjustedJD = julianDate - fractionalDay
    let     timespanCenturies = (adjustedJD - JD_2000) / JulianCentury
    var     GreenwichSiderealSeconds = 24110.54841 +            // Greenwich Mean Sidereal Time (secs)
        timespanCenturies * (8640184.812866 +
            timespanCenturies * (0.093104 -
                timespanCenturies * 0.0000062))
    GreenwichSiderealSeconds = fmod(GreenwichSiderealSeconds + fractionalDay * eRotation * day2sec, day2sec)

    return (360.0 * GreenwichSiderealSeconds * sec2day)
}

**Comment by gavineadie** [comment]
I may have corrected that .. sorry for the mistakes, too much rushing .. Gavin
